# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "elastic/fedora-23-x86_64"
  config.vm.synced_folder "./", "/vagrant_data"
  config.vm.synced_folder "~/Development/gopath/src/github.com/openshift/origin/", "/origin"
  config.vm.provision "setup1", type: "shell", path: "provision-minimal.sh"
  config.vm.provision "setup2", type: "shell", path: "install-openshift.sh"

  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "6000"
  end

end