# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "elastic/fedora-23-x86_64"
  config.vm.network "forwarded_port", guest: 9990, host: 9990
  #config.vm.synced_folder "~/Development/", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.memory = "6000"
  end

  config.vm.provision "shell", inline: <<-SHELL
        # The basics
	yum install -y java-1.8.0-openjdk-devel.x86_64

	# Setup teiid
	wget https://repository.jboss.org/nexus/service/local/repositories/releases/content/org/jboss/teiid/teiid/8.13.4/teiid-8.13.4-wildfly-server.zip
        unzip teiid-8.13.4-wildfly-server.zip
        cd teiid-8.13.4/
   	bin/standalone.sh -c standalone-teiid.xml
  SHELL
end
